name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer valgrind
        run: sudo apt-get update && sudo apt-get install -y valgrind

      - name: Compiler / Vérifier les leaks
        run: make leaks
